import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/sd.github.io/favicon.ico' />
      </Head>

      {/* <main className={styles.main}>
        <Image
          src='/sd.github.io/csunLogo.png'
          alt='Vercel Logo'
          width={1000}
          height={300}
        />
      </main> */}

      <main>
        <Image
          src='/sd.github.io/csunLib1.jpg'
          alt='Vercel Logo'
          layout='fill'
          priority
        />
      </main>

      {/* <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'>
          Powered by{' '}
          <span className={styles.logo}>
            <Image
              src='/sd.github.io/vercel.svg'
              alt='Vercel Logo'
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
